services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1963812368
      MYSQL_DATABASE: estudy_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
  redis:
    image: redis:8.0
    container_name: redis_cache
    command: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro

  nginx:
    image: nginx:trixie
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "5555:5555"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/huypham/Desktop/Repo/Github/estudy/backend/app/storage:/storage:ro
    extra_hosts:
      - "spring.internal:host-gateway"
