spring.application.name=app
spring.profiles.active=dev

spring.datasource.url=jdbc:mysql://localhost:3306/estudy_db?createDatabaseIfNotExist=true
spring.datasource.username=
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true

app.jwt.issuer=estudy
app.jwt.key=
app.jwt.refresh-exp=864000
app.jwt.access-exp=600
app.mail.otp-exp=300

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=5555